// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz_-uJsrUwRXGf3KiWsr4rmB2UK02_Yio',
    appId: '1:146462615171:web:3f155afea782101358ddb6',
    messagingSenderId: '146462615171',
    projectId: 'khonology-buzz-build-web-app',
    authDomain: 'khonology-buzz-build-web-app.firebaseapp.com',
    storageBucket: 'khonology-buzz-build-web-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZXIpuDg31mfdw_kwMi_f3rsbnFxY3sBI',
    appId: '1:146462615171:android:b97f7498cb7d8b0858ddb6',
    messagingSenderId: '146462615171',
    projectId: 'khonology-buzz-build-web-app',
    storageBucket: 'khonology-buzz-build-web-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBToqN3PkKfu9JPDJxpG7DdnSrHF0nmq38',
    appId: '1:146462615171:ios:486afbf9f734ec2f58ddb6',
    messagingSenderId: '146462615171',
    projectId: 'khonology-buzz-build-web-app',
    storageBucket: 'khonology-buzz-build-web-app.firebasestorage.app',
    iosBundleId: 'com.example.khonologyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBToqN3PkKfu9JPDJxpG7DdnSrHF0nmq38',
    appId: '1:146462615171:ios:486afbf9f734ec2f58ddb6',
    messagingSenderId: '146462615171',
    projectId: 'khonology-buzz-build-web-app',
    storageBucket: 'khonology-buzz-build-web-app.firebasestorage.app',
    iosBundleId: 'com.example.khonologyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz_-uJsrUwRXGf3KiWsr4rmB2UK02_Yio',
    appId: '1:146462615171:web:4b0c99fa7a47448f58ddb6',
    messagingSenderId: '146462615171',
    projectId: 'khonology-buzz-build-web-app',
    authDomain: 'khonology-buzz-build-web-app.firebaseapp.com',
    storageBucket: 'khonology-buzz-build-web-app.firebasestorage.app',
  );
}
