name: Trigger Render Deploy

on:
  push:
    branches:
      - khono-v2

jobs:
  trigger-render-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        env:
          RENDER_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          echo "Triggering Render Deploy..."
          curl -X POST "$RENDER_HOOK"
